name = "kate-garden"
compatibility_date = "2025-01-20"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "garden-views"
database_id = "5940b434-65ae-4b2c-aed1-8d80c3d57c1a"
